### ISSUE TITLE
Generalize TestResult model

### ISSUE THREAD

**Issue by RichardBruskiewich** [TranslatorSRI/TranslatorTestingModel#19]
The **TestResultPKSet**  model is not yet general enough, but mainly tailored to the existing _Benchmarking_ testing output. 

We could consider inserting a generic parent '**`TestResult`**' in between '**`TestEntity`**' and '**`TestResultPKSet`**', or even consider renaming the latter to '**`BenchmarkingTestResult`**', although  I'm less certain of needing multiple TestResult child class models... maybe one properly designed model will eventually suffice.

In particular,  the **`ComponentEnum`** could be generalized to leverage the **infores** catalog, I note the explicit list of slots for ARA's being tested (the **TestResultPKSet** is not using the **`ComponentEnum`** and in fact, includes **`unsecret`** which isn't yet even listed in the **`ComponentEnum`**. 

A more extensible general data model might be appropriate here for reporting results.   For example, changing the hard-coded component slots to a single multi-valued in-lined slot ("**`component_test_results`**') of **`ComponentTestResult`** defined as:

```yaml
  ComponentTestResult:
    is_a: TestEntityParameter
    slot_usage:
      parameter:
         range: ComponentEnum
      value:
         description: >-
            The 'value' of should be string descriptive of 
            the test result for a given component.
```

It may be necessary to further constrain the **`ComponentEnum`** definition to only expect Translator component infores identifiers as discussed in https://github.com/TranslatorSRI/TranslatorTestingModel/pull/18.
